name = "gooog"
compatibility_date = "2024-03-20"
pages_build_output_dir = "public"



[[d1_databases]]
binding = "DB"
database_name = "goooog-db"
database_id = "63d1b19a-52de-4000-8869-414b551a3720"
preview_database_id = "63d1b19a-52de-4000-8869-414b551a3720"
migrations_dir = "migrations"
