name = "goooog"
compatibility_date = "2024-03-20"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "CACHE"
id = "mock_production_id_for_cache"
preview_id = "mock_preview_id_for_cache"

[[d1_databases]]
binding = "DB"
database_name = "goooog-db"
database_id = "mock_d1_database_id"
preview_database_id = "mock_d1_database_id"
migrations_dir = "migrations"
